/**
 * Expo config plugin for the local `ringer-control` native module.
 *
 * The Kotlin module is autolinked from `modules/ringer-control`, but a few things
 * have to be declared in the app's AndroidManifest, which the module can't add on
 * its own:
 *
 *   1. `ACCESS_NOTIFICATION_POLICY` — lets the user grant Do Not Disturb access,
 *      required to flip the ringer into/out of silent on Android 6.0+.
 *   2. `RECEIVE_BOOT_COMPLETED` — lets us hear the boot broadcast so the grace
 *      timers (FR-1.4) can be reconciled after a reboot.
 *   3. `RingerTimerReceiver` — fired by AlarmManager when a dwell / exit-buffer
 *      timer elapses (FR-1.4). Not exported and has no intent-filter: it's
 *      delivered via an explicit PendingIntent from our own process.
 *   4. `RingerBootReceiver` — reconciles any grace timer left dangling by a
 *      reboot (AlarmManager alarms don't survive a reboot).
 *
 * Why a plugin and not a hand edit: `android/` is git-ignored and regenerated by
 * `expo prebuild`, so any manual manifest change is wiped. This re-applies all of
 * it on every prebuild. `VIBRATE` is already added by the base Expo template.
 */
const { AndroidConfig, withAndroidManifest } = require('expo/config-plugins');

const TIMER_RECEIVER = 'expo.modules.ringercontrol.RingerTimerReceiver';
const BOOT_RECEIVER = 'expo.modules.ringercontrol.RingerBootReceiver';

module.exports = function withRingerControl(config) {
  config = AndroidConfig.Permissions.withPermissions(config, [
    'android.permission.ACCESS_NOTIFICATION_POLICY',
    'android.permission.RECEIVE_BOOT_COMPLETED',
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      cfg.modResults,
    );
    application.receiver = application.receiver ?? [];

    const hasReceiver = (name) =>
      application.receiver.some((r) => r.$?.['android:name'] === name);

    // Timer receiver: triggered only by our own AlarmManager PendingIntent, so it
    // stays unexported and needs no intent-filter.
    if (!hasReceiver(TIMER_RECEIVER)) {
      application.receiver.push({
        $: {
          'android:name': TIMER_RECEIVER,
          'android:enabled': 'true',
          'android:exported': 'false',
        },
      });
    }

    // Boot receiver: started by the OS on BOOT_COMPLETED, so it must be exported
    // and carry the matching intent-filter.
    if (!hasReceiver(BOOT_RECEIVER)) {
      application.receiver.push({
        $: {
          'android:name': BOOT_RECEIVER,
          'android:enabled': 'true',
          // Must be explicit on API 31+ for components with an intent-filter.
          'android:exported': 'true',
        },
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.intent.action.BOOT_COMPLETED' } },
            ],
          },
        ],
      });
    }

    return cfg;
  });
};
