/**
 * Expo config plugin for the local `auto-silent` native module (EPIC-01).
 *
 * The Kotlin module is autolinked from `modules/auto-silent`, but several things
 * have to be declared in the app's AndroidManifest, which the module can't add
 * on its own:
 *
 *   1. `RECEIVE_BOOT_COMPLETED` — the permission that lets us hear the
 *      "device finished booting" broadcast.
 *   2. A statically-registered `<receiver>` for `BootReceiver`, so the OS starts
 *      our process and re-arms auto-silent after a reboot even if the user never
 *      reopened the app (FR-1.1).
 *   3. `FOREGROUND_SERVICE` + `FOREGROUND_SERVICE_SPECIAL_USE` — let us run the
 *      auto-silent foreground service that keeps the geofence monitor alive on
 *      aggressive OEMs (FR-1.7). `SPECIAL_USE` is the Android 14+ per-type
 *      permission matching the service's declared type.
 *   4. A `<service>` for `AutoSilentService`, declared `specialUse`: the service
 *      holds no continuous resource (it reads no location itself — the OS hands
 *      geofence transitions to the headless task) and is started from the
 *      background after boot, where the while-in-use `location` type is barred on
 *      Android 14+. The `PROPERTY_SPECIAL_USE_FGS_SUBTYPE` property documents the
 *      use for Play review. See `AutoSilentService.kt`.
 *
 * Why a plugin and not a hand edit: `android/` is git-ignored and regenerated by
 * `expo prebuild`, so any manual manifest change is wiped. This re-applies all of
 * it on every prebuild.
 */
const { AndroidConfig, withAndroidManifest } = require('expo/config-plugins');

const BOOT_RECEIVER = 'expo.modules.autosilent.BootReceiver';
const SERVICE = 'expo.modules.autosilent.AutoSilentService';

module.exports = function withAutoSilent(config) {
  config = AndroidConfig.Permissions.withPermissions(config, [
    'android.permission.RECEIVE_BOOT_COMPLETED',
    'android.permission.FOREGROUND_SERVICE',
    'android.permission.FOREGROUND_SERVICE_SPECIAL_USE',
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      cfg.modResults,
    );
    application.receiver = application.receiver ?? [];
    application.service = application.service ?? [];

    const alreadyRegistered = application.receiver.some(
      (receiver) => receiver.$?.['android:name'] === BOOT_RECEIVER,
    );

    if (!alreadyRegistered) {
      application.receiver.push({
        $: {
          'android:name': BOOT_RECEIVER,
          'android:enabled': 'true',
          // Must be explicit on API 31+ for components with an intent-filter.
          'android:exported': 'true',
        },
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.intent.action.BOOT_COMPLETED' } },
            ],
          },
        ],
      });
    }

    const serviceRegistered = application.service.some(
      (service) => service.$?.['android:name'] === SERVICE,
    );

    if (!serviceRegistered) {
      application.service.push({
        $: {
          'android:name': SERVICE,
          // Not exported: started only via explicit Intent from our own process.
          'android:exported': 'false',
          'android:foregroundServiceType': 'specialUse',
        },
        property: [
          {
            $: {
              'android:name':
                'android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE',
              'android:value':
                'Keeps geofence monitoring alive to silence the phone near mosques.',
            },
          },
        ],
      });
    }

    return cfg;
  });
};
