/**
 * Expo config plugin: derive the Android `versionCode` from git history.
 *
 * Android requires `versionCode` to strictly increase on every release or the
 * new APK won't install over the old one. Rather than bumping a number by hand,
 * we inject a Gradle helper that runs `git rev-list --count HEAD` at build time,
 * so each commit produces a unique, monotonically increasing code automatically.
 *
 * Why a Gradle snippet (not a baked number): `android/` is git-ignored and
 * regenerated by `expo prebuild`, and local APKs are built with raw
 * `./gradlew assembleRelease`. A dynamic snippet is re-evaluated on *every*
 * gradle build, so the version tracks git even between prebuilds.
 *
 * `versionName` (the human-facing semantic version) stays manual — set it via
 * `expo.version` in app.json and bump it per release.
 */
const { withAppBuildGradle } = require('expo/config-plugins');

// Gradle helper injected just before the `android { ... }` block. Falls back to
// 1 when git is unavailable (e.g. a tarball with no .git directory).
// Uses ProviderFactory.exec (Gradle 7.5+) rather than the legacy Project.exec
// closure, which no longer runs at configuration time on Gradle 9.x.
const GIT_VERSION_CODE_HELPER = `
// Injected by plugins/withVersionCode.js — versionCode = git commit count.
def getVersionCodeFromGit() {
    try {
        return providers.exec {
            commandLine 'git', 'rev-list', '--count', 'HEAD'
        }.standardOutput.asText.get().trim().toInteger()
    } catch (ignored) {
        return 1
    }
}
`;

module.exports = function withVersionCode(config) {
  return withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // Inject the helper once, immediately before the top-level `android {` block.
    if (!contents.includes('getVersionCodeFromGit')) {
      contents = contents.replace(
        /^android\s*\{/m,
        `${GIT_VERSION_CODE_HELPER}\nandroid {`,
      );
    }

    // Replace the static `versionCode <n>` with a call to the helper.
    contents = contents.replace(
      /versionCode\s+\d+/,
      'versionCode getVersionCodeFromGit()',
    );

    cfg.modResults.contents = contents;
    return cfg;
  });
};
