/**
 * Expo config plugin for the local `auto-silent` native module (EPIC-01).
 *
 * The Kotlin module is autolinked from `modules/auto-silent`, but two things
 * have to be declared in the app's AndroidManifest, which the module can't add
 * on its own:
 *
 *   1. `RECEIVE_BOOT_COMPLETED` — the permission that lets us hear the
 *      "device finished booting" broadcast.
 *   2. A statically-registered `<receiver>` for `BootReceiver`, so the OS starts
 *      our process and re-arms auto-silent after a reboot even if the user never
 *      reopened the app (FR-1.1).
 *
 * Why a plugin and not a hand edit: `android/` is git-ignored and regenerated by
 * `expo prebuild`, so any manual manifest change is wiped. This re-applies both
 * on every prebuild.
 */
const { AndroidConfig, withAndroidManifest } = require('expo/config-plugins');

const BOOT_RECEIVER = 'expo.modules.autosilent.BootReceiver';

module.exports = function withAutoSilent(config) {
  config = AndroidConfig.Permissions.withPermissions(config, [
    'android.permission.RECEIVE_BOOT_COMPLETED',
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      cfg.modResults,
    );
    application.receiver = application.receiver ?? [];

    const alreadyRegistered = application.receiver.some(
      (receiver) => receiver.$?.['android:name'] === BOOT_RECEIVER,
    );

    if (!alreadyRegistered) {
      application.receiver.push({
        $: {
          'android:name': BOOT_RECEIVER,
          'android:enabled': 'true',
          // Must be explicit on API 31+ for components with an intent-filter.
          'android:exported': 'true',
        },
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'android.intent.action.BOOT_COMPLETED' } },
            ],
          },
        ],
      });
    }

    return cfg;
  });
};
