# Generated by Django 4.2.20 on 2026-06-14 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedTile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tile_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('fetched_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='mosque_lat_lng_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mosque',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_mosque_source_external_id'),
        ),
    ]
