# Generated by Django 4.2.20 on 2026-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fetchedtile_mosque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='external_id',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
