# Generated by Django 4.2.20 on 2026-06-15 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mosque_external_id_alter_mosque_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='core.device')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['device', 'updated_at'], name='core_pin_device__49c9a6_idx')],
            },
        ),
    ]
