# Generated by Django 4.2.20 on 2026-06-20 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamicMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('source_label', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('quran', "Qur'an"), ('hadith', 'Hadith'), ('dua', "Du'a"), ('reminder', 'Reminder')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
