# Generated by Django 4.2.20 on 2026-06-22 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_islamicmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='core.device')),
                ('auto_silent_enabled', models.BooleanField(default=True)),
                ('radius_m', models.PositiveIntegerField(default=150)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('prayer_method', models.CharField(choices=[('MuslimWorldLeague', 'Muslim World League'), ('Egyptian', 'Egyptian'), ('Karachi', 'Karachi'), ('UmmAlQura', 'Umm al-Qura'), ('Dubai', 'Dubai'), ('MoonsightingCommittee', 'Moonsighting Committee'), ('NorthAmerica', 'North America'), ('Kuwait', 'Kuwait'), ('Qatar', 'Qatar'), ('Singapore', 'Singapore'), ('Tehran', 'Tehran'), ('Turkey', 'Turkey')], default='MuslimWorldLeague', max_length=32)),
                ('asr_method', models.CharField(choices=[('standard', 'Standard (Shafiʿi)'), ('hanafi', 'Hanafi')], default='standard', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'device settings',
            },
        ),
    ]
