# Generated by Django 4.2.20 on 2026-07-03 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devicesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mosque_public_id', models.CharField(max_length=64)),
                ('mosque_name', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('reason', models.CharField(choices=[('closed', 'Closed / no longer exists'), ('misnamed', 'Wrong name or details'), ('not_a_mosque', 'Not actually a mosque'), ('unspecified', 'Unspecified')], default='unspecified', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosque_reports', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mosque_public_id', 'status'], name='core_mosque_mosque__47f08c_idx'), models.Index(fields=['status', 'created_at'], name='core_mosque_status_76c7e5_idx')],
            },
        ),
    ]
