# Generated by Django 4.2.20 on 2026-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mosquereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='islamicmessage',
            name='source_label_bn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='islamicmessage',
            name='text_bn',
            field=models.TextField(blank=True),
        ),
    ]
